EventAutomation:RegisterNewOption("effects_explosion")
    :SetName("Explosion")
    :SetColor(Color(255,115,0))
    :SetCategory("Effects")
    :AddAttribute("vector", "POSITION_VECTOR", Vector(0, 0, 0), false)
    --:AddAttribute("bool", "ENABLE_AI", true, false)
    :SetServerCallback(function(attributes)
        local explo = ents.Create( "env_explosion" )
        explo:SetKeyValue( "spawnflags", 144 )
        explo:SetKeyValue( "iMagnitude", 15 )
        explo:SetKeyValue( "iRadiusOverride", 256 )
        explo:SetPos(attributes["POSITION_VECTOR"])
        explo:Spawn()
        explo:Fire( "explode", "", 0 )

        local effectdata = EffectData()
        effectdata:SetOrigin(attributes["POSITION_VECTOR"])			
        effectdata:SetScale(10)			
        effectdata:SetRadius(100)		
        effectdata:SetMagnitude(6)			
        util.Effect( "HelicopterMegaBomb", effectdata )
        util.ScreenShake(attributes["POSITION_VECTOR"], 10, 5, 1, 3000 )
    end)
    :SetClientCallback(function(attributes)
        -- client side code here
    end)

if vFireInstalled then
    EventAutomation:RegisterNewOption("effects_vfire")
        :SetName("vFire")
        :SetColor(Color(255,115,0))
        :SetCategory("Effects")
        :AddAttribute("vector", "POSITION_VECTOR", Vector(0, 0, 0), false)
        :AddAttribute("entity", "ENTITY_ID", 0, true)
        --:AddAttribute("bool", "ENABLE_AI", true, false)
        :SetServerCallback(function(attributes)
            local fire = CreateVFireBall(30, 15, attributes["POSITION_VECTOR"], Vector(0, 50, 0))
        end)
        :SetClientCallback(function(attributes)
            -- client side code here
        end)
end